version: '3.7'

services:
  app:
    image: node:12-alpine
    container_name: my_app
    ports:
      - "3030:3030"
    restart: unless-stopped
    #  This tells Compose that we would like to add environment variables from a file called .env, located in our build context.
    env_file: .env
    volumes:
      - ./:/src/
    working_dir: /src/
    command: tail -F -n0 /etc/hosts
